CREATE
    TABLE
        EXOPLANETS(
            ID INTEGER GENERATED BY DEFAULT AS IDENTITY(
                START WITH 0
            ) PRIMARY KEY,
            Planet VARCHAR(255),
            Masse DOUBLE,
            Radius DOUBLE,
            Periode DOUBLE,
            AstroEinheit DOUBLE,
            Exzentrizitaet DOUBLE,
            Bahnneigung DOUBLE,
            Winkelabstand DOUBLE,
            Entdeckung INTEGER,
            Aktualisierung DATE
        );